name: Upload to aws s3
on:
  push:
    branches:
      - master
env:
  AWS_S3_BUCKET: ftr-web-upload-widget-static
  SOURCE_DIST_FOLDER: ./dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: install-dependencies
        run: |
          npm install

      - name: Build
        id: build
        run: |
          npm run build

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to aws s3 bucket
        id: upload-to-s3
        run: |
          aws s3 sync ${{ env.SOURCE_DIST_FOLDER }} s3://${{ env.AWS_S3_BUCKET }} --delete --exclude "*.git*"
